apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

patches:
  - target:
      kind: ConfigMap
      name: my-app-config
    patch: |-
      - op: replace
        path: /data/environment
        value: "development"
