apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

configMapGenerator:
  - name: my-app-config
    literals:
        - ENVIRONMENT=staging
        - LOG_LEVEL=debug

secretGenerator:
  - name: my-app-secrets
    files:
        - db-password.txt
        - api-key.txt
    options:
        disableNameSuffixHash: true
